[net]
    model = "nets/mobilenet_deploy.prototxt"
    weights = "nets/mobilenet.caffemodel"
    input_layers = ["data"]
    output_layers = ["pool6"]
    input_width = 224
    input_height = 224
    normalize = true

    [net.input]
        dimensions = [
            "batch",
            "channel",
            "height",
            "width",
        ]
        channel_ordering = [
            "blue",
            "green",
            "red"
        ]

[mean-image]
    [mean-image.colors]
        blue = 103.94
        green = 116.78
        red = 123.68
