[net]
    model = "nets/yolo_small/yolo_small_deploy.prototxt"
    weights = "nets/yolo_small/yolo_small.caffemodel"
    input_layers = ["data"]
    output_layers = ["fc25"]
    input_width = 448
    input_height = 448

    [net.input]
        dimensions = [
            "batch",
            "channel",
            "height",
            "width",
        ]
        channel_ordering = [
            "blue",
            "green",
            "red",
        ]

[mean-image]
    width = 448
    height = 448
    [mean-image.colors]
        blue = 0.0
        green = 0.0
        red =  0.0
